version: "{build}"

cache:
  - C:\Users\appveyor\clcache
  - third_party/GoogleMock -> cmake/external/GoogleTestNMock.cmake

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: Ninja
      PYTHON: "3.6"
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

platform:
  - x64

configuration:
  - Release

install:
  - set MINICONDA=C:\Miniconda36-x64
  - set PATH=%MINICONDA%;%MINICONDA%/Scripts;%MINICONDA%/Library/bin;%PATH%
  - call scripts\appveyor-setup.bat
  - git submodule -q update --init

build:
  verbosity: minimal

build_script:
  - call scripts\msvc-build.bat

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - ctest --output-on-failure -C %CONFIGURATION%

after_build:
  - clcache -s
